version: "3.7"

services:
  hadabot_ros2_web_bridge_service:
    container_name: hadabot_ros2_web_bridge
    build:
      context: ./
      dockerfile: Dockerfile.ros2_web_bridge
    image: hadabot/ros2-web-bridge:0.3.1_rclnodejs_0_18_2
    ports:
      - "9090:9090"
    networks:
      - hadabot_network
  hadabot_ros2_codeserver_service:
    container_name: hadabot_ros2_codeserver
    build:
      context: ./
      dockerfile: Dockerfile.ros2_codeserver
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    image: hadabot/ros2-codeserver:foxy
    ports:
      - "9123:8080"
      - "9124:80"
      - "9125:5900"
    volumes:
      - ../../hadabot_main:/home/hadabot/hadabot_main
    networks:
      - hadabot_network

networks:
  hadabot_network:
